<?php

namespace App\Models;

use Illuminate\Contracts\Auth\MustVerifyEmail;
use Illuminate\Database\Eloquent\Factories\HasFactory;
use Illuminate\Foundation\Auth\User as Authenticatable;
use Illuminate\Notifications\Notifiable;
use Laravel\Sanctum\HasApiTokens;
use Laravel\Sanctum\PersonalAccessToken;

class User extends Authenticatable
{
    use HasApiTokens, HasFactory, Notifiable;

    /**
     * The attributes that are mass assignable.
     *
     * @var array<int, string>
     */
    protected $fillable = [
        'name',
        'email',
        'password',
        'gender',
        'nik',
        'address',
        'blood_type',
        'phone',
        'emergency_phone',
        'is_admin',
        'is_stakeholder',
        'stakeholder_id'
    ];

    /**
     * The attributes that should be hidden for serialization.
     *
     * @var array<int, string>
     */
    protected $hidden = [
        'password',
        'remember_token'
    ];

    protected $visible = [
        'id',
        'name',
        'email',
        'api_token'
    ];

    /**
     * The attributes that should be cast.
     *
     * @var array<string, string>
     */
    protected $casts = [
        'email_verified_at' => 'datetime',
    ];

    public function stakeholder()
    {
        return $this->belongsTo(Stakeholder::class);
    }

    protected $appends = [
        'api_token',
    ];

    public static function boot()
    {
        parent::boot(); // TODO: Change the autogenerated stub

        self::created(function (self $user) {
            $user->createToken('API Token')->plainTextToken;
        });
    }

    public function getApiTokenAttribute()
    {
        return $this->tokens()->where('name', 'API Token')->first()->token;
    }
}
